name: Mailer
version: 1.3
api-version: 1.17
author: NorthAlaska
main: me.NorthAlaska.mailPlugin.Main
description: Able to send mail to players via books

commands:
  sendMail:
    aliases: [send]
  sendAll:
    
    